### ISSUE TITLE
Leaflet.groupedlayercontrol plugin is not being loaded

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#1921]
### Steps to reproduce the error
1. Using the latest `master` branch, run the website in the dev VM
2. Open a project dashboard page

### Actual behavior
- Project map is blank (no basemap tiles, no control buttons).
- JS console (in Firefox) says: "L.control.groupedLayers is not a function".

### Expected behavior
- Project map shows the base map and map controls.
- No JS errors.

### Notes
I think this is caused when PR #1867 deleted the following lines: https://github.com/Cadasta/cadasta-platform/pull/1867/files#diff-9cefbc5bf4514d16c9e7064813c46069L255

Leaflet.draw is still being loaded because of the django-leaflet plugin we are using. But the other Leaflet plugin is no longer being loaded.

**Comment by alukach** [comment]
@seav Good catch, I can't think of why I would have removed those lines, I'm guessing just a bad merge deconfliction? 🤷‍♂️ Sorry, I should have caught that when reviewing the diff before merging that PR.
