### ISSUE TITLE
AttributeError: 'WSGIRequest' object has no attribute 'user'

### ISSUE THREAD

**Issue by amplifi** [Cadasta/cadasta-platform#1746]
### Steps to reproduce the error

Without logging in, attempt to load a platform URL for creation, such as:

https://platform-staging.cadasta.org/organizations/allthethings/projects/quiet-car/records/locations/new

Also applies to /delete, /edit

_**Edit:** Same error occurs with or without active user session, if trailing slash is not appended to URL_

### Actual behavior

Unhandled Django exception causes a 500 error in uWSGI. See https://opbeat.com/cadasta/platform-staging/errors/209/ for trace. 

### Expected behavior

Redirect to sign in page.

**Comment by amplifi** [comment]
This is related to `APPEND_SLASH`, see https://stackoverflow.com/questions/11223597/django-wsgirequest-object-has-no-attribute-user-on-some-pages for explanation and fix

**Comment by dpalomino** [comment]
As this is also preventing downloading forms from ODK, priority is critical now...

**Comment by amplifi** [comment]
Possibly introduced by the accounts middleware changes in #1726

**Comment by amplifi** [comment]
**Steps to reproduce the error**

Configure ODK with proper credentials
Retrieve xforms via Get Blank Forms
Enjoy the 500
Same behaviour with GeoODK.

**Actual behavior**

See above

**Expected behavior**

Xforms properly downloaded

**Comment by alukach** [comment]
@amplifi great research! surely introduced in #1726
